kind: pipeline
name: default

steps:
  - name: Test
    image: perl:5.28.0
    commands:
      - cpanm -q --notest --no-man-pages --installdeps .
      - cpanm -q --notest --no-man-pages Test2::Harness
      - yath --qvf

  - name: Build
    image: perl:5.28.0
    depends_on:
      - Test
    commands:
      - cpanm -q --notest --no-man-pages App::ModuleBuildTiny
      - git clean -xdf
      - mbtiny dist
      - ls -l

  - &installation
    name: Install (perl 5.30)
    image: perl:5.30
    depends_on:
      - Build
    commands:
      - echo *.tar.gz
      - cpanm --notest -q *.tar.gz
      - cpanm -q *.tar.gz

  - << : *installation
    name: Install (perl 5.28)
    image: perl:5.28

  - << : *installation
    name: Install (perl 5.26)
    image: perl:5.26

  - << : *installation
    name: Install (perl 5.24)
    image: perl:5.24

  - << : *installation
    name: Install (perl 5.22)
    image: perl:5.22

  - << : *installation
    name: Install (perl 5.20)
    image: perl:5.20

  - << : *installation
    name: Install (perl 5.18)
    image: perl:5.18
