#!/usr/bin/env perl
use strict;
use warnings;
use Hijk;
use URI;

my $uri_string = shift or die "$0 <url>";

my $uri = URI->new($uri_string);

my $res = Hijk::request {
    method => "GET",
    host => $uri->host,
    port => $uri->port || 80,
    path => $uri->path,
    query_string => $uri->query,
};

print $res->{body};
